# Generated by Django 4.2.7 on 2023-11-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
