# Generated by Django 4.2.5 on 2023-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.role'),
        ),
    ]
