# Generated by Django 4.2.6 on 2023-10-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verifytoken_jwttoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifytoken',
            old_name='user',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='jwttoken',
            name='user',
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.account'),
        ),
    ]
